#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Sep  7 13:27:06 2021

@author: gabriel
Monte Carlo Ibov
"""
import pandas as pd
import matplotlib.pyplot as fig
import numpy as np
from scipy.stats import norm

df=pd.read_excel('Ibovespa.xls',sheet_name='IBV')

list=['Ibov']
fig.figure()
ax1=fig.subplot(211)
ax1.plot(df.Data,df[list],'-k',alpha=1)
fig.title('Ibovespa (2015-2021)',fontsize=16)
ax1.legend(list)

for i in range(1):
        ax1.text(x=df.Data[-1:],y=df[list[i]][-1:],
                 s=list[i],fontsize=10,color='k',weight='bold')
n=len(df)
#+++++++++++++++++ exclui a coluna de datas para o calculo do retorno
prec=df.drop(['Data'],axis=1)
#+++++++++++++++++ retorno dos precos 
ri=prec/prec.shift(1)-1
mi=ri.mean().values     # retorno medio dos ativos por coluna
sigma=ri.std()          #desvio padrao
ax1=fig.subplot(212)
ax1.plot(df.Data,ri,'-k',alpha=1)
fig.xlabel('Anos ',fontsize=16)
fig.ylabel('Retornos',fontsize=16)
#++++++++++++  Histograma e curva normal do ativo 
fig.figure()
ax1=fig.subplot(111)
ax1.hist(np.asarray(ri, dtype='float'),bins=10,density=True,
         color='black',alpha=0.4)
xmin,xmax=fig.xlim()
eixox=np.linspace(xmin,xmax,100)
eixoy=norm.pdf(eixox,mi,sigma)
ax1.plot(eixox,eixoy,'--k',linewidth=3)
fig.xlabel('faixas de retornos financeiros ',fontsize=16)
fig.title('histograma de retornos - Ibovespa (2015-2021)',fontsize=16)
#++++++++++++ simulacao de Monte Carlo
x=np.zeros((n,5))
for j in range(5):
    for i in range(n):
        x[i,j]=np.random.normal(mi,sigma)
        

fig.figure()
fig.plot(df.Data,ri,'-k')
fig.plot(df.Data,x,'-k',alpha=0.2)
fig.xlabel('Anos ',fontsize=16)
fig.ylabel('Retornos',fontsize=16)
fig.title('Simulacao de Monte Carlo para retornos do IBOV(2015-2021)',fontsize=16)

print('')
print('+++++++ RESULTADO DA SIMULACAO DE MONTE CARLO +++++++')
print('RETORNO MEDIO REAL = ',float(mi)*252)
print('RETORNO MEDIO SIMULADO = ',x.mean()*252)
print('VOLATILIDADE REAL = ',float(sigma)*252)
print('VOLATILIDADE SIMULADA = ',x.std()*252)




